### ISSUE TITLE
GUI for Displaying List of Courses

### ISSUE THREAD

**Issue by itscoe** [itscoe/CS390#1]
**Describe the solution you'd like**
All users of the registration system will have the capability to login in to the system and display a list of courses.  Create a GUI that implements these transactions for students, faculty, and administrators as given in the Group Project Specification.  Read login and course information from start-up input files.  Also, update your UML diagrams as needed.

**Additional context**
Assignment #2. See chapter 17 for examples of how to read input files.

**Comment by dswetlik** [comment]
New method to open files in the back-end.
Push the filename through method BuildFilePath(string fileName) into OpenFile(string fileName).
I would explain exactly what this does and how it works, but I don't want to.
Just trust me that it works.

**Comment by itscoe** [comment]
All users currently have the capacity to log in

**Comment by itscoe** [comment]
The requirements for this issue have been met. Good work team
